---
title: "FINAL PROJECT (MODEL BASED)"
author: "Ummar A. Sallil"
date: "2022-12-14"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Helper packages
```{r}
library(dplyr)    
library(ggplot2)   
library(gridExtra)  
library(tidyverse) 
library(cluster)    
library(factoextra)
library(readr)
```
# loading dataset
```{r}
radiomics <- read_csv("radiomics.csv")
str(radiomics)
summary(radiomics)
View(radiomics)
```
# Scaling radiomics and excluding the institution and failure binary.
```{r}
df <- scale(radiomics[c(3:431)])
sum(is.na(df))
```
# Modeling packages
```{r}
library(mclust)   # for fitting clustering algorithms
```
# Apply GMM model with 3 components awith a scale of 1:10 to fit the figure in the canvast.
```{r}
rad_mc <- Mclust(df[,1:10], G=3)
summary(rad_mc)
```
#  Plot results
```{r}
plot(rad_mc, what = "density")
plot(rad_mc, what = "uncertainty")
```
# Observations with high uncertainty
```{r}
sort(rad_mc$uncertainty, decreasing = TRUE) %>% head()
rad_optimal_mc <- Mclust(df[,1:10])
summary(rad_optimal_mc)
```

```{r}
legend_args <- list(x = "bottomright", ncol = 5)
plot(rad_optimal_mc, what = 'BIC', 
     legendArgs = list(x = "bottomright", ncol = 5))
plot(rad_optimal_mc, what = 'classification')
plot(rad_optimal_mc, what = 'uncertainty')
```
```{r}
library(stringr)  # provides consistent wrappers and simplifies the manipulation of character strings.
```
```{r}
probabilities <- rad_mc$z 
colnames(probabilities) <- paste0('C', 1:3)
```

```{r}
probabilities <- probabilities %>%
  as.data.frame() %>%
  mutate(id = row_number()) %>%
  tidyr::gather(cluster, probability, -id)
```

```{r}
ggplot(probabilities, aes(probability)) +
  geom_histogram() +
  facet_wrap(~ cluster, nrow = 2)
```
```{r}
uncertainty <- data.frame(
  id = 1:nrow(radiomics),
  cluster = rad_mc$classification,
  uncertainty = rad_mc$uncertainty
)
```
```{r}
uncertainty %>%
  group_by(cluster) %>%
  filter(uncertainty > 0.25) %>%
  ggplot(aes(uncertainty, reorder(id, uncertainty))) +
  geom_point() +
  facet_wrap(~ cluster, scales = 'free_y', nrow = 1)
```
```{r}

cluster2 <- df %>%
  scale() %>%
  as.data.frame() %>%
  mutate(cluster = rad_mc$classification) %>%
  filter(cluster == 2) %>%
  select(-cluster)
```

```{r}

cluster2 %>%
  tidyr::gather(product, std_count) %>%
  group_by(product) %>%
  summarize(avg = mean(std_count)) %>%
  ggplot(aes(avg, reorder(product, avg))) +
  geom_point(color = "blue", alpha = .7, size = 1) +
  labs(x = "Average standardized consumption", y = NULL)
```







